Merci\UserBundle\Entity\User:
    type: entity
    table: User
    repositoryClass: Merci\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: '40'
        salt:
            type: string
            length: 32
    manyToOne:
        address:
            targetEntity: Address
            inversedBy: users
            cascade: ["persist"]
    #para varios campos utilizar joinColumns no mesmo nivel do relacionamento
    joinColumn:
            name: address_id
            referencedColumnName: id
    lifecycleCallbacks: {  }