Merci\CatalogBundle\Entity\Product:
    type: entity
    table: Product
    repositoryClass: Merci\CatalogBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        description:
            type: text
        price:
            type: decimal
            scale: 2
        imagePath:
            type: string
            length: '255'
            column: image_path
    lifecycleCallbacks: {  }
