homepage:
    pattern:  /
    defaults: { _controller: MerciCatalogBundle:Default:index }

product:
  pattern: /product/{id}
  defaults: { _controller: MerciCatalogBundle:Default:product }
  requirements:
    id: \d+