parameters:
#    merci_catalog.example.class: Merci\CatalogBundle\Example

services:
#    merci_catalog.example:
#        class: %merci_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    merci.twig.catalog_extension:
        class: Merci\CatalogBundle\Twig\CatalogExtension
        tags:
            - { name: twig.extension }