login:
    pattern:  /login
    defaults: { _controller: MerciUserBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

register:
    pattern: /register
    defaults: { _controller: MerciUserBundle:Default:register }

account:
    pattern: /account
    defaults: { _controller: MerciUserBundle:Default:account }